[variables]
echo_correlation_key = "echo#unique"

[[test_suites]]
process_id = "echo_process"
message_name = "Echo"
message_key = "${echo_correlation_key}"

[test_suites.api_call]
endpoint = "http://localhost:6969/echo"
method = "POST"
payload = '{"hello": "world", "from": "flow-sentry", "message-key": "${echo_correlation_key}"}'
headers = '{"Content-Type": "application/json"}'

[[test_suites.test_cases]]
flow_node_id = "Echo API Call"
expected_variables = """
{
  "hello": "world",
  "from": "flow-sentry"
}
"""

[[test_suites.test_cases]]
flow_node_id = "Termination"
expected_variables = """
{
  "hello": "world",
  "from": "flow-sentry"
}
"""

